[package]
authors = ["callumjhays <callumjhays@gmail.com>"]
name = "backend"
version = "0.1.0"
[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
serde = "1.0.11"
serde_derive = "1.0.11"

[dev-dependencies]
serde_json = "1.0.2"
